-- 코드를 입력하세요
    -- 날짜 계산 임시테이블 (AVG_TABLE)
    WITH CAL_DATE_TABLE AS
    (
        SELECT CAR_ID
             , ROUND(AVG((DATEDIFF(END_DATE, START_DATE) + 1)), 1)   AVERAGE_DURATION
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      GROUP BY CAR_ID
      ORDER BY CAR_ID
    )
    
    # SELECT * FROM CAL_DATE_TABLE
    
    SELECT CAR_ID
         , AVERAGE_DURATION
      FROM CAL_DATE_TABLE
     WHERE AVERAGE_DURATION >= 7
  ORDER BY AVERAGE_DURATION DESC
         , CAR_ID DESC
     