-- 코드를 입력하세요
    SELECT BK.BOOK_ID
         , ATH.AUTHOR_NAME
         , DATE_FORMAT(BK.PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE
      FROM BOOK     BK
INNER JOIN AUTHOR   ATH
        ON BK.AUTHOR_ID = ATH.AUTHOR_ID
     WHERE CATEGORY = '경제'
  ORDER BY BK.PUBLISHED_DATE